name: Upload Artifact
description: Upload Artifact
inputs:
  sourcePath:
    description: Source path of the artifact
    required: true
  configuration:
    description: 'Build Configuration i.e. debug, production, automation'
    required: true
    default: debug
  buildVersion:
    description: Build Version
    required: true
  buildNumber:
    description: Build Number
    required: true

runs:
  using: composite
  steps:
    - name: Set Publish Repo
      run: |
        if [[ ${{ inputs.configuration }} = "release" ]]; then
          echo "PUBLISH_REPO=prod" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Print Publish Repo
      run: |
        echo "Publish Repo: ${{ env.PUBLISH_REPO }}"
      shell: bash

    - name: Print Build Version
      run: |
        echo "Build Version: ${{ inputs.buildVersion }}"
      shell: bash

    - name: Set Configuration
      run: |-
        if [[ ${{ inputs.configuration }} = "Production" ]]; then
           echo "LOWERCASE_CONFIGURATION=production" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Execute JFrog CLI commands (Copy ipa/apk file)
      run: |
        jfrog rt u "${{ inputs.sourcePath }}" "${{ env.PUBLISH_REPO }}/com/blackberry/${{ env.PRODUCT }}/mobile/${{ env.LOWERCASE_CONFIGURATION }}/${{ env.PRODUCT }}_mobile/${{ inputs.buildVersion }}.${{ inputs.buildNumber }}/${{ env.PRODUCT }}_mobile-${{ inputs.buildVersion }}.${{ inputs.buildNumber }}-${{ env.LOWERCASE_PLATFORM }}.${{ env.ARTIFACT_EXT }}"
      shell: bash

    - name: Add build Info
      run: |
        jfrog rt bce "${{ github.workflow }}" ${{ github.run_number }}
        jfrog rt bp "${{ github.workflow }}" ${{ github.run_number }}
      shell: bash