name: CI/CD Prod Workflow

on:
  workflow_dispatch:
    # Input to be taken to Run this workflow
    inputs:
      buildtype:
        description: 'Build Type[Automation|debug|release]'
        required: true
        default: 'release'

jobs:
  build:
    name: CI/CD Prod OnDemandBuild
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      ## Checkout the repository ###
      - name: Checkout Main Repository
        uses: actions/checkout@v3

      ## Prepare OS and Java environment
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: gradle

      ## Make Gradle Executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build the project and generate APK with Gradle
      - name: Build & Generate app APK
        run: ./gradlew assembleRelease --stacktrace

      - uses: r0adkll/sign-android-release@v1
        name: Sign artifact
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      ############## Artifactory related steps START ####################
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_ENV_1: ${{ secrets.JF_ARTIFACTORY_SECRET }}

      - name: Upload to Artifactory
        id: upload-to-artifactory
        uses: ./.github/actions/common/upload-artifact
        with:
          sourcePath: ${{ steps.sign_app.outputs.signedReleaseFile }}
          configuration: ${{ github.event.inputs.buildtype }}
          buildVersion: '13.2.15'
          buildNumber: 2215

